# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gGqelR3mkgKN-jx23E0iIT6ygAEmfImX
"""

def kasallik_tashxisi(belgi):
  if belgi == "tish og'rig'i":
    return "trimol iching"
  elif belgi == "bosh og'rig'i":
    return "bolnol iching"
  elif belgi == "allergiya":
    return "diazolin iching"
  elif belgi == "gripp":
    return "taylol hot iching"
  elif belgi == "ko'z og'rig'i":
    return "tetraskilin maz surting"
  elif belgi == "oyoq og'rig'i":
    return "qupen iching"
  elif belgi == "oshqozon og'rig'i":
    return "noshpa iching"
  elif belgi == "isitma":
    return "parasetamol iching"
  elif belgi == "bel og'rig'i":
    return "indometatsin maz surting"
  elif belgi == "shikastlanish":
      return "shifokorga murojat qiling"
  else:
    return "Shifokorga murojat qiling"
belgi=input("Kasallik belgisini kiriting ")
natija=kasallik_tashxisi(belgi)
print(natija)